name: audacious-qt
base: core22
adopt-info: audacious-qt
summary: Lightweight Open Source Qt based Music player
description: |
  Audacious is a Lightweight Qt + Music Player.
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64
    
layout:
  /usr/lib/audacious:
    symlink: $SNAP/usr/lib/audacious

apps:
  audacious-qt:
    command: usr/bin/audacious
    extensions:
    - kde-neon
    common-id: org.community.audacious-qt
    
    plugs:
      - home
      - audio-playback
      - alsa
      - gsettings
      - pulseaudio
      - bluez
      - bluetooth-control
      - media-control
      - network-status
      - network
      - network-bind
      - raw-usb
      - optical-drive
      - network-status
      - removable-media
      - unity7
      - screen-inhibit-control
      
 
 
      
parts:
  audacious-qt:
    source: https://github.com/audacious-media-player/audacious.git
    plugin: autotools
    autotools-configure-parameters: 
       - --prefix=/usr
       - --disable-gtk
       - --enable-qt
       - --disable-dbus
       - --with-buildstamp='Snapcraft'
       
    override-pull: |
      craftctl default
       craftctl set version=$(git describe --tags --abbrev=0)
      
    build-snaps:
      - cmake
      - ubuntu-make
      
    build-packages:
      - curl
      - build-essential
      - make
      - git
      - autotools-dev
      - automake
      - autoconf
      - autopoint
      - libtool
      - libkf5doctools-dev
      - libphonon4qt5-dev
      - libphonon4qt5experimental-dev
      - libglib2.0-0
      - libaudcore5
      - libstdc++6
      - libgcc-s1
      - libc6
      - unzip
      

          
    stage-packages:
      - libcue2
      - liblirc-client0
      - liblirc0
      - libadplug-2.3.3-0
      - libbinio1v5
      - libsdl2-2.0-0
      - libxss1
      - libdecor-0-0
      - libfluidsynth3
      - libinstpatch-1.0-2
      - libcddb2
      - libcdio19
      - libcdio-cdda2
      - libopusfile0
      - libpipewire-0.3-0
      - libsndio7.0
      - libmms0
      - libneon27
     
    override-stage: |
      craftctl default
      sed -i -e '/^plugin_dir=/s/\${exec_prefix}/\/usr/' usr/lib/pkgconfig/audacious.pc  
       
  audacious-plugins:
    after: [audacious-qt]
    source: https://github.com/audacious-media-player/audacious-plugins.git 
    plugin: autotools
    autotools-configure-parameters:
       - --prefix=/usr
       - --disable-gtk
       - --enable-qt
       
    build-snaps:
      - cmake
      - ubuntu-make
    
    build-packages:
      - curl
      - build-essential
      - make
      - git
      - autotools-dev
      - automake
      - libglib2.0-dev
      - libglib2.0-dev-bin
      - libglib2.0-0
      - libkf5doctools-dev
      - libphonon4qt5-dev
      - libphonon4qt5experimental-dev
      - autoconf
      - autopoint
      - libtool
      - libtool-bin    
      - libcdio19
      - libcdio-utils
      - libcdio-dev
      - libcdio-cdda2
      - libcdio-cdda-dev
      - libcdio++-dev
      - libcdio++1
      - libcddb2
      - libcddb2-dev
      - libadplug-2.3.3-0
      - libadplug-dev
      - adplug-utils
      - oggfwd
      - oggz-tools
      - libvorbis-dev
      - libvorbis0a
      - vorbisgain
      - xmms2-plugin-all
      - libopus-dev
      - libopus0
      - libopusfile-dev
      - libopusfile0
      - opus-tools
      - flac
      - libflac++-dev
      - libflac++6v5
      - libflac-dev
      - libflac8
      - fluidsynth
      - libfluidsynth-dev
      - libfluidsynth3
      - libmpg123-0
      - libmpg123-dev
      - wavpack
      - libwavpack-dev
      - libwavpack1
      - libcue2
      - libcue-dev
      - libpipewire-0.3-0
      - libpipewire-0.3-common
      - libpipewire-0.3-dev
      - libpipewire-0.3-modules
      - libspa-0.2-bluetooth
      - libspa-0.2-dev
      - libspa-0.2-jack
      - libspa-0.2-modules
      - libneon27
      - libneon27-dev
      - libgtk2.0-dev
      - libgtk2.0-0
      - libgtk2.0-bin
      - ffmpeg
      - libmms0
      - libmms-dev
      - faac
      - libjson-glib-dev
      - aac-enc
      - libavcodec-extra
      - libavformat-extra
      - libavutil56
      - libmodplug1
      - libopenmpt0
      - libopenmpt-modplug1
      - libsidplayfp6
      - libbs2b0
      - libsamplerate0
      - libsoxr0
      - libsoxr-lsr0
      - lirc
      - liblirc-client0
      - liblirc0
      - liblirc-dev
      - liblirc0
      - pulseaudio-module-lirc
      - lirc-x
      - lirc-drv-irman
      - libaudcore5

      
   
    
  
   
      
     
  
 
      
      
      
     
   
   
